name: Run-Jest-Unit-Tests

on:
  workflow_dispatch:      
  pull_request:
    branches:
      - main
      - release

jobs:
  Run-Jest-Unit-Tests:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'hifibuild' && github.event.pusher.name != 'dependabot'

    steps:
      - name: View Commit Author
        run: echo "The last push was made by a user named ${{ github.event.pusher.name }}."
      
      - uses: actions/checkout@v2
    
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Modules
        run: npm i

      # Run unit tests
      - name: Run Jest Unit Tests
        shell: bash
        run: |
          ./node_modules/.bin/jest unit --ci --useStderr 2>&1 | tee testoutput
          ./testfails.sh

      # Final testing status for repo
      - name: All Tests Passed
        if: success()
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "success", "description": "Tests passed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'

      - name: Any Test Failed
        if: failure()
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "failure", "description": "Tests failed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
